export class QuizBank {
    constructor() {
        this.questions = []
        this.initializeQuestions()
    }

    /**
     * Initializes the array of questions for the QuizBank.
     */
    initializeQuestions() {
        this.questions = [
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "What is the capital of France?",
                correct_answer: "Paris",
                incorrect_answers: ["London", "Berlin", "Madrid"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "Who wrote the play 'Romeo and Juliet'?",
                correct_answer: "William Shakespeare",
                incorrect_answers: ["George Orwell", "Jane Austen", "Charles Dickens"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "Which gas do plants absorb from the atmosphere?",
                correct_answer: "Carbon Dioxide",
                incorrect_answers: ["Oxygen", "Nitrogen", "Hydrogen"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "What is the largest mammal in the world?",
                correct_answer: "Blue Whale",
                incorrect_answers: ["African Elephant", "Giraffe", "Hippopotamus"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "Who painted the Mona Lisa?",
                correct_answer: "Leonardo da Vinci",
                incorrect_answers: ["Vincent van Gogh", "Pablo Picasso", "Michelangelo"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "What is the national flower of Japan?",
                correct_answer: "Cherry Blossom",
                incorrect_answers: ["Rose", "Tulip", "Sunflower"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "In which year did the Titanic sink?",
                correct_answer: "1912",
                incorrect_answers: ["1907", "1915", "1923"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "What is the largest organ in the human body?",
                correct_answer: "Skin",
                incorrect_answers: ["Liver", "Heart", "Lungs"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "Who is the author of 'To Kill a Mockingbird'?",
                correct_answer: "Harper Lee",
                incorrect_answers: ["F. Scott Fitzgerald", "Mark Twain", "Charles Dickens"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "Which gas is responsible for the Earth's ozone layer?",
                correct_answer: "Oxygen",
                incorrect_answers: ["Carbon Dioxide", "Nitrogen", "Hydrogen"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "What is the currency of Japan?",
                correct_answer: "Japanese Yen",
                incorrect_answers: ["Chinese Yuan", "Korean Won", "Indian Rupee"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "Who is the founder of Microsoft?",
                correct_answer: "Bill Gates",
                incorrect_answers: ["Steve Jobs", "Mark Zuckerberg", "Jeff Bezos"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "Which famous scientist formulated the theory of relativity?",
                correct_answer: "Albert Einstein",
                incorrect_answers: ["Isaac Newton", "Stephen Hawking", "Galileo Galilei"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "What is the largest ocean in the world?",
                correct_answer: "Pacific Ocean",
                incorrect_answers: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "Who was the first woman to fly solo across the Atlantic Ocean?",
                correct_answer: "Amelia Earhart",
                incorrect_answers: ["Bessie Coleman", "Jacqueline Cochran", "Harriet Quimby"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "What is the chemical symbol for gold?",
                correct_answer: "Au",
                incorrect_answers: ["Ag", "Fe", "Cu"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "Which country is known as the Land of the Rising Sun?",
                correct_answer: "Japan",
                incorrect_answers: ["China", "Korea", "Vietnam"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "What is the largest desert in the world?",
                correct_answer: "Sahara Desert",
                incorrect_answers: ["Gobi Desert", "Atacama Desert", "Arabian Desert"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "Who wrote the play 'Hamlet'?",
                correct_answer: "William Shakespeare",
                incorrect_answers: ["George Bernard Shaw", "Anton Chekhov", "Tennessee Williams"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "What is the chemical symbol for water?",
                correct_answer: "H2O",
                incorrect_answers: ["CO2", "O2", "N2"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "What is the largest planet in our solar system?",
                correct_answer: "Jupiter",
                incorrect_answers: ["Saturn", "Mars", "Venus"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "Which famous scientist developed the theory of evolution by natural selection?",
                correct_answer: "Charles Darwin",
                incorrect_answers: ["Albert Einstein", "Isaac Newton", "Marie Curie"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "What is the currency of Germany?",
                correct_answer: "Euro",
                incorrect_answers: ["Mark", "Pound Sterling", "Dollar"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "Which continent is the driest and has the largest desert on Earth?",
                correct_answer: "Africa",
                incorrect_answers: ["Australia", "Asia", "North America"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "Who is the author of the novel '1984'?",
                correct_answer: "George Orwell",
                incorrect_answers: ["Aldous Huxley", "Ray Bradbury", "J.K. Rowling"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "What gas do plants release during photosynthesis?",
                correct_answer: "Oxygen",
                incorrect_answers: ["Carbon Dioxide", "Nitrogen", "Hydrogen"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "Which planet is known as the 'Morning Star'?",
                correct_answer: "Venus",
                incorrect_answers: ["Mercury", "Mars", "Jupiter"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "Who painted the 'Starry Night'?",
                correct_answer: "Vincent van Gogh",
                incorrect_answers: ["Pablo Picasso", "Leonardo da Vinci", "Claude Monet"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "In which year did World War II end?",
                correct_answer: "1945",
                incorrect_answers: ["1939", "1950", "1940"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "What is the chemical symbol for iron?",
                correct_answer: "Fe",
                incorrect_answers: ["Au", "Ag", "Cu"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "Which country is known as the 'Land of the Midnight Sun'?",
                correct_answer: "Norway",
                incorrect_answers: ["Sweden", "Finland", "Iceland"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "What is the national flower of India?",
                correct_answer: "Lotus",
                incorrect_answers: ["Rose", "Tulip", "Sunflower"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "Who wrote the play 'Macbeth'?",
                correct_answer: "William Shakespeare",
                incorrect_answers: ["Arthur Miller", "Oscar Wilde", "George Bernard Shaw"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "What is the largest bird in the world?",
                correct_answer: "Ostrich",
                incorrect_answers: ["Emu", "Penguin", "Eagle"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "Which gas makes up the majority of Earth's atmosphere?",
                correct_answer: "Nitrogen",
                incorrect_answers: ["Oxygen", "Carbon Dioxide", "Hydrogen"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "Who was the first woman to win a Nobel Prize?",
                correct_answer: "Marie Curie",
                incorrect_answers: ["Rosa Parks", "Amelia Earhart", "Mother Teresa"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "What is the longest river in the world?",
                correct_answer: "Nile",
                incorrect_answers: ["Amazon", "Mississippi", "Yangtze"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "Who wrote the famous novel 'Pride and Prejudice'?",
                correct_answer: "Jane Austen",
                incorrect_answers: ["Emily Brontë", "Charlotte Brontë", "George Eliot"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "What is the chemical symbol for silver?",
                correct_answer: "Ag",
                incorrect_answers: ["Au", "Fe", "Cu"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "Which planet is known as the 'Red Planet'?",
                correct_answer: "Mars",
                incorrect_answers: ["Jupiter", "Saturn", "Mercury"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "Which gas do humans breathe out when they exhale?",
                correct_answer: "Carbon Dioxide",
                incorrect_answers: ["Oxygen", "Nitrogen", "Hydrogen"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "What is the largest continent on Earth?",
                correct_answer: "Asia",
                incorrect_answers: ["Africa", "North America", "Europe"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "Who is the author of 'The Great Gatsby'?",
                correct_answer: "F. Scott Fitzgerald",
                incorrect_answers: ["Ernest Hemingway", "J.D. Salinger", "William Faulkner"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "What is the chemical symbol for hydrogen?",
                correct_answer: "H",
                incorrect_answers: ["O", "N", "C"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "In which year did the Berlin Wall fall?",
                correct_answer: "1989",
                incorrect_answers: ["1979", "1999", "2009"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "What is the smallest prime number?",
                correct_answer: "2",
                incorrect_answers: ["1", "3", "5"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "Who is known as the 'Father of Modern Physics'?",
                correct_answer: "Albert Einstein",
                incorrect_answers: ["Isaac Newton", "Galileo Galilei", "Niels Bohr"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "What is the chemical symbol for sodium?",
                correct_answer: "Na",
                incorrect_answers: ["K", "Mg", "Ca"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "Which country is known for its famous canals in Venice?",
                correct_answer: "Italy",
                incorrect_answers: ["Greece", "Spain", "France"],
            },
            {
                category: "General Knowledge",
                type: "multiple",
                difficulty: "medium",
                question: "What is the largest species of shark?",
                correct_answer: "Whale Shark",
                incorrect_answers: ["Great White Shark", "Tiger Shark", "Hammerhead Shark"],
            },
        ]
    }

    /**
     * Retrieves the questions from the QuizBank.
     * @returns {Array} The array of questions.
     */
    getQuestions() {
        return this.questions
    }
}
